#pragma once 

typedef enum {

    LIQUID_OK = 0,
    LIQUID_ERROR_UNKNOWN = -1, // Weired Error

    // Core
    LIQUID_ERROR_CORE_UNKNOWN = -100,
    
    LIQUID_ERROR_NOT_INITIALIZED = -101,

    // Canvas
    LIQUID_ERROR_CANVAS_NULL = -200,
    LIQUID_ERROR_CANVAS_INVALID_ARG = -201,
    LIQUID_ERROR_CANVAS_OUT_OF_MEMORY = -202,

    // Image
    LIQUID_ERROR_IMAGE_NOT_FOUND = -300,
    LIQUID_ERROR_IMAGE_LOAD_FAILED = -301,
    LIQUID_ERROR_IMAGE_UNSUPPORTED_FORMAT = -302,

    // Font
    LIQUID_ERROR_FONT_NOT_FOUND = -400,
    LIQUID_ERROR_FONT_UNSUPPORTED_FORMAT = -401,
    LIQUID_ERROR_FONT_LOAD_FAILED = -402,

    // File
    LIQUID_ERROR_FILE_NOT_FOUND = -500,
    LIQUID_ERROR_UNSUPPORTED_FILE_FORMAT = -501,
    LIQUID_ERROR_INVALID_ASSET_URL = -502,

    // Event System
    LIQUID_ERROR_EVENT_SYSTEM = -600,

    // User Error
    LIQUID_ERROR_INVALID_ARGUMENT = -700,
    LIQUID_ERROR_OUT_OF_MEMORY = -701,
    LIQUID_ERROR_INVALID_OPERATION = -702,

} LiQuidError;

const char* LQErrorToString(LiQuidError error);